upstream pfme-api {
    keepalive 32;
    server pfme-api:80;
}

upstream postfixadmin {
    keepalive 32;
    server postfixadmin:9000;
}

server {
    listen 80 default_server;
    server_name _;

    root /var/www/html/public;

    location /api/ {
        proxy_pass http://pfme-api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $forwarded_proto;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_buffering off;
        proxy_request_buffering off;
    }

    location / {
        index index.php;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass postfixadmin;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
