-- database:  ${POSTFIXADMIN_DB_NAME}
--
-- Copyright 2025 William W. Kimball, Jr. MBA MSIS
--
CREATE TABLE IF NOT EXISTS ${DBSCHEMA_SETTINGS_TABLE} (
    id      BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
    , name  VARCHAR(255) UNIQUE NOT NULL
    , value TEXT NULL
    , created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    , updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO ${DBSCHEMA_SETTINGS_TABLE} (name, value) VALUES
    ('pfme_schema_version', '20250518-1')
;
