-- database:  ${POSTFIXADMIN_DB_NAME}
--
-- Copyright 2025 William W. Kimball, Jr. MBA MSIS
--
REVOKE ALL PRIVILEGES ON `${POSTFIXADMIN_DB_NAME}`.* FROM '${POSTFIXADMIN_DB_USER}'@'${POSTFIXADMIN_SOURCE_NETWORK}';

DROP USER '${POSTFIXADMIN_DB_USER}'@'${POSTFIXADMIN_SOURCE_NETWORK}';

DROP DATABASE ${POSTFIXADMIN_DB_NAME};
