-- database:  ${POSTFIXADMIN_DB_NAME}
--
-- Copyright 2025 William W. Kimball, Jr. MBA MSIS
--
CREATE DATABASE IF NOT EXISTS `${POSTFIXADMIN_DB_NAME}`;

CREATE USER IF NOT EXISTS '${POSTFIXADMIN_DB_USER}'@'${POSTFIXADMIN_SOURCE_NETWORK}' IDENTIFIED BY '${POSTFIXADMIN_DB_PASSWORD}';

GRANT ALL PRIVILEGES ON `${POSTFIXADMIN_DB_NAME}`.* TO '${POSTFIXADMIN_DB_USER}'@'${POSTFIXADMIN_SOURCE_NETWORK}';

FLUSH PRIVILEGES;
